### PR TITLE
Upload large number of tests (>20K) in chunks to prevent Snowflake errors

### LINKED ISSUE #255: Uploading tests fails on a large repo with 19K+ tests
We have a large repo with 19K+ tests, the `uploading tests` step started to fail with the following error:
```
>dbt --cache-selected-only run --selector lexis_nexis --target sub
17:00:44  Running with dbt=1.3.0
17:00:59  Found 2694 models, 19362 tests, 351 snapshots, 9 analyses, 856 macros, 1 operation, 20 seed files, 1671 sources, 0 exposures, 0 metrics
17:00:59
17:01:05  Concurrency: 1 threads (target='sub')
17:01:05
17:01:05  1 of 1 START sql view model prep_sub.lexis_nexis.tmx_session_log_deluxe ........ [RUN]
17:01:09  1 of 1 OK created sql view model prep_sub.lexis_nexis.tmx_session_log_deluxe ... [SUCCESS 1 in 3.86s]
17:01:09
17:01:09  Running 1 on-run-end hook
17:01:09  Uploading model executions
17:01:12  Uploading seed executions
17:01:12  Uploading snapshot executions
17:01:12  Uploading test executions
17:01:12  Uploading exposures
17:01:12  Uploading tests
17:01:20  Database error while running on-run-end
17:01:21  Encountered an error:
Database Error
  001795 (42601): SQL compilation error: error line 14 at position 13
  maximum number of expressions in a list exceeded, expected at most 16,384, got 19,362
```
^ this is a known Snowflake limitation on the length of the query. It could be resolved by inserting the data in the loop.

### PR DESCRIPTION
**Pull request by nhrebinka**
## Overview

This fixes the problem of uploading a large number of tests into Snowflake. [This issue](https://github.com/brooklyn-data/dbt_artifacts/issues/255) describes the problem in more details.

This version of code has been tested locally for 4+ months as we could not use `dbt_artifacts`'s original version which was breaking prod jobs.

## Update type - breaking / non-breaking

- [x] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What does this solve?

https://github.com/brooklyn-data/dbt_artifacts/issues/255

## What databases have you tested with?

- [x] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A

### CODE REVIEW

File: macros/upload_results.sql [hunk 1]
```diff
@@ -78,14 +78,23 @@
...
-        }}
+        {% set tests_set = [] %}
+        {% for node in graph.nodes.values() | selectattr("resource_type", "equalto", "test") %}
+            {% do tests_set.append(node) %}
+        {% endfor %}
+        {# upload tests in chunks of 5000 tests, or less #}
+        {% set upload_limit = 5000 %}
+        {% set n = (tests_set|length/upload_limit)|round(0, 'ceil')|int %}
+        {% for i in range(n) -%}
+            {% set content_tests = upload_tests(tests_set, i+1, upload_limit) %}
```
Comment (glsdown) [inline macros/upload_results.sql]: I believe this is why the integration tests are currently failing:

```suggestion
            {% set content_tests = dbt_artifacts.upload_tests(tests_set, i+1, upload_limit) %}
```

File: macros/upload_results.sql [hunk 2]
```diff
@@ -78,14 +78,23 @@
...
-            table_name=tests.identifier,
-            content=content_tests
-            )
-        }}
+        {% set tests_set = [] %}
+        {% for node in graph.nodes.values() | selectattr("resource_type", "equalto", "test") %}
+            {% do tests_set.append(node) %}
+        {% endfor %}
+        {# upload tests in chunks of 5000 tests, or less #}
+        {% set upload_limit = 5000 %}
```
Comment (glsdown) [inline macros/upload_results.sql]: This looks like it would also be a great solution for #232 although BigQuery typically has a lower limit. So I wonder if it would be good to include something like this here:

```suggestion
        {% set upload_limit = 750 if target.type == 'bigquery' else 5000 %}
```

File: macros/upload_results.sql [hunk 3]
```diff
@@ -78,14 +78,23 @@
...
+        {% set n = (tests_set|length/upload_limit)|round(0, 'ceil')|int %}
+        {% for i in range(n) -%}
```
Comment (glsdown) [inline macros/upload_results.sql]: Rather than complicate the `upload_tests` macros by passing in the additional parameters, it might be worth instead only passing in the slice of the tests list that we want to use:

```sql
        {%- for i in range(0, tests_set | length, upload_limit) -%}
            {% set content_tests = dbt_artifacts.upload_tests(tests_set[i: i + upload_limit]) %}
            {{ dbt_artifacts.insert_into_metadata_table(
                database_name=tests.database,
                schema_name=tests.schema,
                table_name=tests.identifier,
                content=content_tests
                )
            }}
        {% endfor -%}
```

This means that the logic in the individual `default__get_tests_dml_sql` and `bigquery__get_tests_dml_sql` shouldn't need to change. It will also mean that those macros don't have to loop through the entire list of tests on each run, so should speed things up.

**Review by glsdown — CHANGES_REQUESTED** [review]
Thank you so much for putting the effort into building this, and creating a great addition.

I've left some comments around suggested improvements for efficiency, as well as to fix the failing CI checks. Let me know if you have any questions.

P.S. apologies for the weird commit and revert at the end - I was on the wrong branch when I pushed 🤦

File: macros/upload_results.sql (hunk 3 above)
Comment (nhrebinka) [reply macros/upload_results.sql]: thanks @glsdown, excellent suggestion!

**Comment by nhrebinka** [comment]
@glsdown it is ready for integration testing. I ran some basic testing locally, looks good and uploads the right # of tests.

**Review by glsdown — APPROVED** [review]
This looks great, and is a really useful enhancement - thank you for taking the time to do it.
