### PR TITLE
Fix cartesian join bug

### LINKED ISSUE #103: Refactor of granularity in tables.
#81 migrated several OR statements into a consistent `artifact_run_id`. This was a good improvement but results in a few tricky issues about granularity.

Situation:
- dbt cloud job, which runs `seed`, `run` and `test` (I don't believe the problem I'm highlighting would occur in the case of running `build`).
- After each step we run `upload_artifacts` macros.
- The created artifacts would have `run_results` for each step, with each of the models/tests/seeds executed at each step (which is good) and _also_ a duplicate manifest for each, with a different `command_invocation_id` but the _same_ `artifact_run_id`.
- The current proposed `MERGE` statements in #99 don't solve this situation currently because we're merging on `artifact_run_id` AND `atrifact_generated_at`.
- This means that when we start joining on `artifact_run_id` in models we get a cartesian join and more rows than we need. Most specifically in `stg_dbt__node_executions`, but also in `fct_dbt__snapshot_executions`, `fct_dbt__seed_executions` & `fct_dbt__model_executions`.

I think the solution to this is to change the join in these cases to join _only_ on `command_invocation_id` which is unique to a given artifact - and avoids the cartesian join.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This resolves #103 . The right granularity in these tables in command_invocation_id regardless of whether in cloud or local.

### CODE REVIEW

File: models/incremental/fct_dbt__model_executions.sql [hunk 1]
```diff
@@ -35,10 +35,7 @@ model_executions_with_materialization as (
         models.name
     from model_executions_incremental
     left join models on
-        (
-            model_executions_incremental.command_invocation_id = models.command_invocation_id
-            or model_executions_incremental.dbt_cloud_run_id = models.dbt_cloud_run_id
-        )
+        model_executions_incremental.command_invocation_id = models.command_invocation_id
```
Comment (NiallRees) [inline models/incremental/fct_dbt__model_executions.sql]: Just so I understand, how come not `artifact_run_id` in all these?

Comment (NiallRees) [reply models/incremental/fct_dbt__model_executions.sql]: I just re-read the associated issue. Does removing the join on `dbt_cloud_run_id` not just undo https://github.com/brooklyn-data/dbt_artifacts/pull/38 and make this incompatible with dbt Cloud? Running the upload macro causes the manifest to be re-created and gives it a new command_invocation_id per https://github.com/brooklyn-data/dbt_artifacts/issues/53.

Comment (alanmcruickshank) [reply models/incremental/fct_dbt__model_executions.sql]: Depends on our intent.
1. Based on my reading of #19 and #38- the idea was to only upload the manifest once - then allow ever set of related results to upload. That means `artifact_run_id` makes sense as the key for joining here because you can rely on there only being one.
2. The intent here changes that and assumes each run of the upload macro creates a new manifest - which is then directly joined to. That means that `command_invocation_id` is the right key to join on here.

To avoid a cartesian join I think we need to be clear on what we expect to be duplicated and what we expect to be unique in the dbt cloud "multi-upload" case.

The more I think about this - re-uploading the manifest does seem a bit wasteful and maybe rather than this PR - I need to modify the V2 upload so that the manifest gets overwritten rather than duplicated. @NiallRees thoughts?

Comment (NiallRees) [reply models/incremental/fct_dbt__model_executions.sql]: If we can achieve a state where we only have one of each unique manifest, that is definitely advantageous. Did you see  my note
> Running the upload macro causes the manifest to be re-created and gives it a new command_invocation_id per https://github.com/brooklyn-data/dbt_artifacts/issues/53.

Comment (alanmcruickshank) [reply models/incremental/fct_dbt__model_executions.sql]: Ok - let me rethink this PR. Will change the intent.

Comment (alanmcruickshank) [reply models/incremental/fct_dbt__model_executions.sql]: Hmmm - actually this could be tricky. Will slack you.

**Comment by alanmcruickshank** [comment]
@NiallRees - this is ready for re-review. It should now:
- Dedupe V2 manifests on upload.
- Dedupe V1 manifests on read.
- Join exclusively on `artifact_run_id` in later models.

File: macros/upload_artifacts_v2.sql [hunk 2]
```diff
@@ -153,7 +153,9 @@
         {{ flatten_manifest("raw_data") }}
 
     ) as new_data
-    on old_data.command_invocation_id = new_data.command_invocation_id and old_data.node_id = new_data.node_id
+    -- NB: We dedupe on artifact_run_id rather than command_invodation_id for manifest nodes
```
Comment (NiallRees) [inline macros/upload_artifacts_v2.sql]:
```suggestion
    -- NB: We dedupe on artifact_run_id rather than command_invocation_id for manifest nodes
```

**Comment by NiallRees** [comment]
Looks like there are a couple of linting errors but everything else is working now @alanmcruickshank
