### PR TITLE
Enforce consistency across materialised models.

### LINKED ISSUE #75: Failure in test not_null_fct_dbt__latest_full_model_executions_node_id
We're intermittently experiencing this failure:

```
Failure in test not_null_fct_dbt__latest_full_model_executions_node_id (models/schemas.yml)
  Got 1 result, configured to fail if != 0

  compiled SQL at target/compiled/dbt_artifacts/models/schemas.yml/schema_test/not_null_fct_dbt__latest_full_model_executions_node_id.sql
```

On inspection this happens when a new upload coincides with an incremental run of the package. Due to (what I'm pretty sure is...) a race condition means that while the most recent run is present in `fct_dbt__run_results`, it is not present in `fct_dbt__model_executions` - and so the most recent run appears to have no model executions. The current workaround is to run a full rebuild, which take significant time.

A better solution would be to only allow runs which *have* model executions in this model. It adds complexity but would explicitly eliminate this race condition.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This fixes #75 by enforcing consistency between the `run_results` model and all the other incremental models. I've also added a section in the docs to explain what that is and a link to the original issue.

This doesn't yet solve the other issue (#76), but I'll address that in a subsequent PR.

### CODE REVIEW

File: models/incremental/int_dbt__model_executions.sql [hunk 1]
```diff
@@ -11,6 +11,7 @@ model_executions_incremental as (
 
     select *
     from model_executions
+    -- NOTE: Consitency check for this model is done in the fact table not here. See: fct_dbt__model_executions.
```
Comment (NiallRees) [inline models/incremental/int_dbt__model_executions.sql]:
```suggestion
    -- NOTE: Consistency check for this model is done in the fact table not here. See: fct_dbt__model_executions.
```

**Review by NiallRees — APPROVED** [review]
