### PR TITLE
Fix missing value in upload model executions - add else clause to for if loops

### LINKED ISSUE #385: [Bug]: Error from snowflake__get_model_executions_dml_sql missing value
## Overview

When called following a failed call to a macro, the insert into model_executions generated is missing a value. "Inconsistent number of values in the VALUES clause expecting 16 but got 15".

## How to reproduce

Build a model that calls a macro which raises a user defined compiler error "do exceptions.raise_compiler_error(err)"
Call dbt_artifacts.upload_results(results) to upload results.

## Expected behaviour

Generation of a valid insert statement with the required 16 values from the snowflake__get_model_executions_dml_sql macro. 

Within the {% if model.timing != [] %} block need additional "{% else %} null" block for each  {% for stage in model.timing if stage.name == "<stage name>" %} to catch missing stage times within timing.

## Screenshots

image

## Environment

Results of running `dbt --version`: 1.6.2

```sh
1.6.2
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
    - package: dbt-labs/dbt_utils
    version: 1.1.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.0
  - package: dbt-labs/audit_helper
    version: 0.6.0
  - package: calogica/dbt_expectations
    version: 0.8.5
    # <see https://github.com/calogica/dbt-expectations/releases/latest> for the latest version tag
  - package: brooklyn-data/dbt_artifacts
    version: 2.5.0
```

### PR DESCRIPTION
**Pull request by kenpokiwi**
## Overview

See details in #385 

## Update type - breaking / non-breaking

- [x] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What does this solve?

Resolves #385 

## What databases have you tested with?

- [ ] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] Postgres
- [ ] N/A

### CODE REVIEW

File: macros/upload_individual_datasets/upload_model_executions.sql [hunk 1]
```diff
@@ -179,6 +179,8 @@
                         {% else %}
                             '{{ stage.started_at }}', {# compile_started_at #}
                         {% endif %}
+                    { % else %}
+                        null, {# compile_started_at #}
                     {% endfor %}
```
Comment (glsdown) [inline macros/upload_individual_datasets/upload_model_executions.sql]: I think originally this `loop.length` section was designed for the use-case you are fixing here, but doesn't make sense (it wouldn't run if the loop was empty). That means it can be removed I believe. Looking at the logic here, it also looks like it could be hugely simplified using Jinja filtering:

```
                {% set compile_started_at = (model.timing | selectattr("name", "eq", "compile") | first | default({})).get("started_at") %}
                {% if compile_started_at %}'{{ compile_started_at }}'{% else %}null{% endif %}, {# compile_started_at #}
                {% set query_completed_at = (model.timing | selectattr("name", "eq", "execute") | first | default({})).get("completed_at") %}
                {% if query_completed_at %}'{{ query_completed_at }}'{% else %}null{% endif %}, {# query_completed_at #}
```

I think this would aid readability and consistency. What do you think?

Comment (kenpokiwi) [reply macros/upload_individual_datasets/upload_model_executions.sql]: Yes I think that is much more elegant :)

Comment (glsdown) [reply macros/upload_individual_datasets/upload_model_executions.sql]: Thanks for looking at this. For consistency, please could you also add the same logic into the other two macros in here for BQ and Snowflalke? From lines 88 and 164. Thanks!

Comment (kenpokiwi) [reply macros/upload_individual_datasets/upload_model_executions.sql]: Thanks for the feedback. Update done.

**Review by glsdown — APPROVED** [review]

File: macros/upload_individual_datasets/upload_model_executions.sql [hunk 2]
```diff
@@ -97,20 +86,10 @@
...
-                    {% if loop.length == 0 %}
-                        null, {# query_completed_at #}
-                    {% else %}
-                        '{{ stage.completed_at }}', {# query_completed_at #}
-                    {% endif %}
+                    {% set compile_started_at = (model.timing | selectattr("name", "eq", "compile") | first | default({})).get("started_at") %}
+                    {% if compile_started_at %}'{{ compile_started_at }}'{% else %}null{% endif %}, {# compile_started_at #}
+                    {% set query_completed_at = (model.timing | selectattr("name", "eq", "execute") | first | default({})).get("completed_at") %}
+                    {% if query_completed_at %}'{{ query_completed_at }}'{% else %}null{% endif %}, {# query_completed_at #}
                 {% endfor %}
```
Comment (glsdown) [inline macros/upload_individual_datasets/upload_model_executions.sql]:
```suggestion
```

**Review by glsdown — CHANGES_REQUESTED** [review]

**Review by glsdown — APPROVED** [review]

**Comment by glsdown** [comment]
Thanks for all your work on this!
